#!/bin/bash

#Git link for documentation
git_link="http://repo.antiersolutions.com/surinder.k/git-hooks"

# Minimum and maximum allowed lengths for the commit message
min_length=20
max_length=500

# Read the commit message from the temporary file
commit_message_file=$1
commit_message=$(cat "$commit_message_file")

# Get the length of the commit message
length=${#commit_message}

# Check the length of the commit message
if [ "$length" -lt "$min_length" ]; then
    echo "Error: Commit message length is too short (minimum $min_length characters) required." >&2
    echo "Documentation: $git_link"
    exit 1
elif [ "$length" -gt "$max_length" ]; then
    echo "Error: Commit message length is too long (maximum $max_length characters) allowed." >&2
    echo "Documentation: $git_link"
    exit 1
fi