#!/bin/bash

#Git link for documentation
git_link="http://repo.antiersolutions.com/surinder.k/git-hooks"

# Get the current branch name
branch_name=$(git symbolic-ref --short HEAD)

# Define the desired pattern
#pattern="^(feature|bug)\/[a-z]+([a-z0-9]+)*([a-z]+)?(_[a-z0-9]+(\.[0-9]+)?)?$"
pattern="^(feature|bug)\/[a-z]+([a-z0-9]+)*([a-z]+)?(_[a-z0-9]+(\.[a-z0-9]+)?)*?$"

# Define allowed branches
allowed_branches=("master" "main" "dev" "stage" "hotfix" "bug" "uat" "qa" "design")

# Check if the branch name is allowed
if [[ " ${allowed_branches[@]} " =~ " $branch_name " ]]; then
    exit 0
fi

# Check if the branch name matches the pattern
if [[ ! $branch_name =~ $pattern ]]; then
    echo "Error: Branch name '$branch_name' does not match the required pattern."
    echo "Default branch names allowed: [${allowed_branches[@]}]"
    echo "If you are creating a feature or bug branch, Please rename your branch to one of the following and push again:"
    echo "
    - feature/signup
    - feature/signup_validate
    - feature/signup_v1
    - feature/signup_v1.0
    - feature/signup_validate_f2a
    - feature/signup_11
    - bug/nftid_24_34
    - bug/nft_user_23_421
    - bug/login_page_error.fix_1.2
    - feature/search_bar_improvement.v2
    - bug/api_response_parsing.debug_2.0
    - bug/payment_gateway_integration_issue.debug
    - feature/user_management.enhance
    - bug/login_page_error.fix_1.2
    - feature/search_bar_improvement.v2
    - bug/api_response_parsing.debug_2.0
    - feature/data_migration_tool.develop
    - bug/report_generation_failure.investigate_3
    - feature/user_interface_redesign.prototype
    - bug/cache_invalidation_issue.resolve_patch
    - feature/notification_system.implement_v1
    - invalid_string_here ->invalid
    - feature/UserSignup ->invalid
    "
    echo "Documentation: $git_link"
    exit 1
fi

# Check if the branch name length is within the desired range (7 to 58)
# branch name could be 50 characters long after feature/{50 characters length}
branch_length=${#branch_name}
if ((branch_length < 7 || branch_length > 58)); then
    echo "Error: Branch name '$branch_name' length should be between 7 and 58 characters."
    echo "Documentation: $git_link"
    exit 1
fi