#!/bin/bash

#Git link for documentation
git_link="http://repo.antiersolutions.com/surinder.k/git-hooks"

# Define the name of the environment file you want to check
ENV_FILE=".env"

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Check if the environment file is among the staged files
if [[ $STAGED_FILES =~ $ENV_FILE ]]; then
  echo "Warning: The ($ENV_FILE) file should not be pushed to the Git server. Please ensure that it is excluded from the code."
  echo "Documentation: $git_link"
exit 1
fi