#!/bin/bash

# Its global server webhook

while read oldrev newrev refname; do
  branch_name=$(git rev-parse --symbolic --abbrev-ref $refname)

  # Enforce standard branch names (e.g., feature/, bugfix/)
#   if [[ ! $branch =~ ^(feature/|bugfix/|hotfix/|release/|main|master)$ ]]; then
#     echo "Error: Invalid branch name '$branch'. Please use a standard branch name."
#     exit 1
#   fi

  # Get the current branch name
    # branch_name=$(git symbolic-ref --short HEAD)

    # Define the desired pattern
    pattern="^feature/[a-z]+(_[a-z0-9]+)*(_[a-z]+)?(_[a-z0-9]+(\.[0-9]+)?)?$"

    # Define allowed branches
    allowed_branches=("master" "main" "dev" "stage" "hotfix" "bug" "uat" "qa" "design")

    # Check if the branch name is allowed
    if [[ " ${allowed_branches[@]} " =~ " $branch_name " ]]; then
        exit 0
    fi

    # Check if the branch name matches the pattern
    if [[ ! $branch_name =~ $pattern ]]; then
        echo "Error: Branch name '$branch_name' does not match the required pattern: feature/{name}*"
        exit 1
    fi

    # Check if the branch name length is within the desired range (10 to 58)
    # branch name could be 50 characters long after feature/{50 characters length}
    branch_length=${#branch_name}
    if ((branch_length < 10 || branch_length > 58)); then
        echo "Error: Branch name '$branch_name' length should be between 10 and 58 characters."
        exit 1
    fi

done