#!/bin/bash

#Git link for documentation
git_link="http://repo.antiersolutions.com/surinder.k/git-hooks"

# Define the name of the environment file you want to check
ENV_FILE=".env"
PACKAGE_LOCK="package-lock.json"

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Check if the environment file is among the staged files
if [[ $STAGED_FILES =~ $ENV_FILE ] || [ $STAGED_FILES == $PACKAGE_LOCK ]]; then
  echo "Warning: The ($STAGED_FILES) file should not be pushed to the Git server. Please ensure that it is excluded from the code."
  echo "Documentation: $git_link"
  exit 1
fi

# Check if node_modules are part of the commit
if git diff --cached --name-only | grep -q 'node_modules/'; then
  echo "Warning: The 'node_modules/' folder should not be pushed to the Git server. Please ensure that it is excluded from the code."
  echo "Documentation: $git_link"
  exit 1
fi